name: Generate Inventory CSV

on:
  # Permite a execução manual através do separador 'Actions' do GitHub
  workflow_dispatch:
  
  # Dispara sempre que há um push no branch principal
  push:
    branches:
      - main
    paths:
      # Só corre se houver alteração na pasta 'emblemas'
      - 'emblemas/**'

env:
  # ----------------------------------------------------------------
  # AJUSTE CONCLUÍDO: O caminho da pasta que contém as suas imagens.
  # ----------------------------------------------------------------
  IMAGES_PATH: 'emblemas'
  
jobs:
  generate_csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Instala o utilitário jq (embora não seja estritamente necessário para este script)
      - name: Setup environment
        run: sudo apt-get install jq -y
          
      - name: Generate CSV Content
        id: generate
        run: |
          # Define o branch principal para a URL RAW (mantenha 'main')
          BRANCH_NAME="main"
          # Cabeçalhos do CSV
          echo "Nome,Categoria,Stock,LinkImagem" > inventory.csv
          
          # Obtém a URL base para o conteúdo RAW
          REPO_URL="https://raw.githubusercontent.com/${{ github.repository }}/${BRANCH_NAME}/${{ env.IMAGES_PATH }}"
          
          # Lista todos os ficheiros de imagem na pasta especificada
          find ${{ env.IMAGES_PATH }} -maxdepth 1 -type f | while read -r file_path; do
            # Extrai apenas o nome do ficheiro (ex: Emblema_Politecnico.jpg)
            filename=$(basename "$file_path")
            
            # Garante que é um tipo de imagem comum (png, jpg, jpeg, gif, webp)
            if [[ "$filename" =~ \.(jpg|jpeg|png|gif|webp)$ ]]; then
              # 1. Nome: Remove a extensão para usar como Nome
              name_only="${filename%.*}"
              
              # 4. LinkImagem: Constrói o URL RAW completo
              link_imagem="${REPO_URL}/${filename}"
              
              # 2. Categoria e 3. Stock: Valores padrão que pode ajustar manualmente no Sheets
              category="Emblema"
              stock=1
              
              # Adiciona a linha ao CSV (separador é a vírgula)
              echo "$name_only,$category,$stock,$link_imagem" >> inventory.csv
            fi
          done
          
      - name: Commit and Push CSV
        # Esta ação fará o commit do novo inventory.csv
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ACCIÓN: Inventário CSV atualizado'
          files: 'inventory.csv'
